### ISSUE TITLE
Build fails when using the 'metamodel' configuration

### ISSUE THREAD

**Issue by dcominottim** [radcortez/openjpa-gradle-plugin#1]
Using the following configuration

```
openjpa {
    persistenceXml = file('src/META-INF/persistence.xml')
	
    includes 'src/com/test/*.java'

    metamodel {
        metamodelOutputFolder 'src/com/test'
        metamodelDependency 'org.apache.openejb.patch:2.3.0-nonfinal-1540826'
    }
}
```

the build fails with the following error

> Could not find method metamodelOutputFolder() for arguments [src/com/test] on object of type com.radcortez.gradle.plugin.openjpa.OpenJpaExtension.

**Comment by radcortez** [comment]
Hi @dcominottim 

Thank you for using the plugin and reporting the bug. Let me have a look into it and I'll get back to you.

Cheers,

**Comment by radcortez** [comment]
Hi @dcominottim 

I've made a change that should fix the issue. Please, update to 1.1 and let me know how it looks. Thank you.

Cheers,

**Comment by dcominottim** [comment]
Hello @radcortez

It seems to be working fine now. Thanks a lot for the great plugin and quick response/fix. Cheers!

**Comment by radcortez** [comment]
Great! Let me know if you need anything else.
