### ISSUE TITLE
Publish on plugins.gradle.org

### ISSUE THREAD

**Issue by ieugen** [radcortez/openjpa-gradle-plugin#12]
It would be great to be able to use `plugins { id 'radcortez.openjpa' version xxx }` to use the plugin instead of the buildscript + apply .

Publishing the plugin is pretty straight forward https://plugins.gradle.org/docs/submit

**Comment by radcortez** [comment]
Hi @ieugen.

Yes, this plugin was done before that. Do you want to try to push a PR to support it? :)

**Comment by ieugen** [comment]
I'm using it as part of a gradle migration. 
https://issues.apache.org/jira/browse/JAMES-3260 

Let's see how it goes.

**Comment by radcortez** [comment]
Ok :)

If you can't do it, let me know and I'll try to find some time to do it.

**Comment by ieugen** [comment]
It's mostly a nice to have for me atm so it's not that high a priority.

Some feedback so far: I see the plugin always runs on the classes, even if nothing has changed. 
Have you looked at gradle task inputs and task outputs to enable caching?

By publishing the plugin you will make it more visible ( i search plugins.gradle.org first ).

**Comment by radcortez** [comment]
The plugin is now available in the Gradle Plugin Portal: https://plugins.gradle.org/plugin/com.radcortez.openjpa.gradle.plugin
