### ISSUE TITLE
Could not find com.radcortez.gradle:openjpa-gradle-plugin:3.1.0

### ISSUE THREAD

**Issue by Shamil-kv** [radcortez/openjpa-gradle-plugin#15]
Getting 404 error While downloading the openJpa-gradle plugin using gradle project. Getting following error.

> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.radcortez.gradle:openjpa-gradle-plugin:3.1.0.
     Searched in the following locations:
       - https://jcenter.bintray.com/com/radcortez/gradle/openjpa-gradle-plugin/3.1.0/openjpa-gradle-plugin-3.1.0.pom
       - https://plugins.gradle.org/m2/com/radcortez/gradle/openjpa-gradle-plugin/3.1.0/openjpa-gradle-plugin-3.1.0.pom
     Required by:
         project :

**Comment by adeosu** [comment]
I am getting a similar error while building my project. Please a solution would be highly appreciated

**Comment by rishabh-99** [comment]
Its not the best solution, buy you can download the project, build the branch you need (3.1.0) and publish it to localMaven using
`./gradlew publishToMavenLocal` command. 
You can use this to build it locally, I am trying to figure out how to do it for Docker images too.
If anyone knows how we can publish it to some repository online please help

Edit: We can copy the local ~/.m2 folder onto docker image before building

**Comment by Shamil-kv** [comment]
@rishabh-99. sorry I didn't get you. For building the project, openjpa-gradle is required. so from where will I get it?

**Comment by yerson117** [comment]
Hi everyone, I just discovered that the JAR file of the plugin has been deleted from the JCenter Maven repository, which provides public access to our applications. I'm unsure if any of you are aware of where we can find an alternative version or if there is a way to improve the JPA entities that utilize OpenJPA.

https://repo1.maven.org/maven2/com/radcortez/

**Comment by yerson117** [comment]
Additionally, I attempted to download the project and compile it locally to obtain the JAR file, but I encountered an issue where some dependencies of the project are also unavailable on JCenter.

**Comment by yerson117** [comment]
I have successfully retrieved the JAR file from my last compilation. I have attached it here for you. Please check if it works for you as well.
[openjpa-gradle-plugin.zip](https://github.com/radcortez/openjpa-gradle-plugin/files/11849541/openjpa-gradle-plugin.zip)

**Comment by radcortez** [comment]
Ok, let me try to push this somewhere else.

**Comment by radcortez** [comment]
The plugin is now available in the Gradle Plugin Portal: https://plugins.gradle.org/plugin/com.radcortez.openjpa.gradle.plugin
