### ISSUE TITLE
Any planned release with recent updates?

### ISSUE THREAD

**Issue by kunickiaj** [radcortez/openjpa-gradle-plugin#5]
Just wanted to check if you plan to publish a new release with the recent changes merged.

**Comment by radcortez** [comment]
Hi @kunickiaj,

I did a release with the latest fixes. You can find it here:
https://bintray.com/radcortez/radcortez/openjpa-gradle-plugin/3.0.0

Is there something missing?

**Comment by radcortez** [comment]
Hey @kunickiaj,

Everything ok?

**Comment by kunickiaj** [comment]
👍
